title: Lathifa Shafa W # your name (or website title) here
logo: "/images/shafaimage.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing my third year Bachelor of Information System at Gunadarma University.
  <br><br>
  I am an diligent, ambitious person who has developed a mature and responsible approach to any task that I undertake, or situation that I am presented with. 
  <br><br>
  <a href="https://www.linkedin.com/in/lathifa-shafa-wibowo-004928218/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
